USE JsonDocsExample;
GO


CREATE TABLE docsexample.pkg_type (
	ID_TYPE INT PRIMARY KEY,
	TYPE VARCHAR(20) NOT NULL,
	CONSTRAINT TYPE_UNQ UNIQUE (TYPE),
	CONSTRAINT TYPE_CHK CHECK (TYPE = UPPER(TYPE))
);

CREATE TABLE docsexample.documents_facts (
	ID_ENTRY INT PRIMARY KEY,
	ID_PKG_TYPE INT,
	CREATED_AT DATE,
	PERIOD VARCHAR(7),
	INCOMES INT DEFAULT 0,
	EXPENSES INT DEFAULT 0,
	CONSTRAINT docs_f_incms_chk CHECK (INCOMES >= 0),
	CONSTRAINT docs_f_expns_chk CHECK (EXPENSES >= 0),
	FOREIGN KEY (ID_PKG_TYPE) REFERENCES docsexample.pkg_type(ID_TYPE)
);